# spring.datasource.url=jdbc:mysql://localhost:3306/tablename
# spring.datasource.username=root
# spring.datasource.password=letmeinplease
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# spring.jpa.properties.hibernate.format_sql=true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: letmeinplease
    # driver-class-name: org.mysql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    # database-platform: org.hibernate.dialect.MySQL8Dialect
