# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Free resources
      run: sudo /etc/init.d/mysql stop
    - name: Set up JDK 17
      uses: actions/setup-java@main
      with:
        java-version: 17
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    - name: Run mysql
      run: sudo /etc/init.d/mysql start
    - name: Execute Jar file
      run: lsof -i :8080 & sudo java -jar /home/ubuntu/api/_work/SpringBoot3SecurityJWT/SpringBoot3SecurityJWT/target/security-0.0.1-SNAPSHOT.jar &
